# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://github.com
baseurl: /jlopezmartinez/
title: Jesús Manuel López
author: Jesús Manuel López
description: Jesús Manuel López profile
avatar: profile.jpg
email: jesus.lopezmar@gmail.com
github: hjlopezmartinez # username
twitter: jlopez_rz
linkedin: jesuslopezmartinez
stackoverflow: users/1484779/jlopez
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
